version: '3'

services:

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=root123
      - POSTGRES_USER=root
      - POSTGRES_DB=coindb

  redis:
    image: 'redis:latest'
    container_name: 'redis'
    restart: 'always'
    ports:
      - 6379:6379
    expose:
      - '6379'

volumes:
  postgres_data:
    driver: local